import { DeployFunction } from "hardhat-deploy/types";
import type { Deployment } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import fs from "fs";
import path from "path";

const FRONTEND_CONFIG_PATH = path.resolve(__dirname, "..", "app", "src", "config", "contracts.ts");

function renderFrontendConfig(fund: Deployment, token: Deployment): string {
  return `// This file is auto-generated by deploy/deploy.ts when deploying to Sepolia.
// Do not edit manually.

export const FUND_ADDRESS = '${fund.address}';
export const FETH_ADDRESS = '${token.address}';

export const TOKEN_DECIMALS = 6;

export const FUND_ABI = ${JSON.stringify(fund.abi, null, 2)};

export const FETH_ABI = ${JSON.stringify(token.abi, null, 2)};
`;
}

function writeFrontendConfig(fund: Deployment, token: Deployment) {
  fs.writeFileSync(FRONTEND_CONFIG_PATH, renderFrontendConfig(fund, token), "utf8");
}

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  const deployedFHEETH = await deploy("FHEETH", {
    from: deployer,
    log: true,
  });

  const deployedEncryptedFund = await deploy("EncryptedFund", {
    from: deployer,
    args: [deployedFHEETH.address],
    log: true,
  });

  console.log(`FHEETH contract: `, deployedFHEETH.address);
  console.log(`EncryptedFund contract: `, deployedEncryptedFund.address);

  if (hre.network.name === "sepolia") {
    const fundDeployment = await hre.deployments.get("EncryptedFund");
    const tokenDeployment = await hre.deployments.get("FHEETH");
    writeFrontendConfig(fundDeployment, tokenDeployment);
    console.log(`Frontend config updated at ${FRONTEND_CONFIG_PATH}`);
  }
};
export default func;
func.id = "deploy_encryptedFund"; // id required to prevent reexecution
func.tags = ["FHEETH", "EncryptedFund"];
